steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcloud-slim', '--tag=gcr.io/donnetsecondapp/gcloud-slim', '-f', 'Dockerfile.slim', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/donnetsecondapp/gcloud', '-f', 'Dockerfile', '.']
