# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Simple sanity check: invoke the new gcloud container to confirm that it was
# built correctly.
- name: 'gcr.io/$PROJECT_ID/gcloud'
  args: ['info']

# Confirm that auth is piped through correctly.
- name: 'gcr.io/$PROJECT_ID/gcloud'
  args: ['builds', 'list']

images:
- 'gcr.io/$PROJECT_ID/gcloud'

timeout: 2400s
