steps:
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'dotnet'
  args: [ 'restore']
  dir: 'SecondApp'
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'dotnet'
  args: [ 'build']
  dir: 'SecondApp'    
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'dotnet'
  args: [ 'publish', '-c', 'Release' ]
  dir: 'SecondApp'

